name: Deploy to AWS # Workflow name displayed in GitHub Actions interface.

on:
  push:
    branches:
      - main # Trigger the workflow on a push to the 'main' branch.
  workflow_dispatch: # Allow manual execution of the workflow from the GitHub Actions interface.

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # AWS Access Key securely stored in GitHub Secrets.
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS Secret Key securely stored in GitHub Secrets.
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }} # AWS region where the infrastructure is deployed.

jobs:
  deploy-test:
    name: Deploy to Test Environment # Job name for deploying to the test environment.
    runs-on: ubuntu-latest # Use the latest Ubuntu virtual machine provided by GitHub Actions.

    steps:
      # Step 1: Check out the code.
      - name: Checkout code # A descriptive name for the step.
        uses: actions/checkout@v3 # Official GitHub Action to clone the repository into the runner.

      # Step 2: Setup Terraform CLI.
      - name: Setup Terraform # Install and configure the Terraform CLI in the GitHub Actions environment.
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 3: Install dependencies and package the Lambda function.
      - name: Install dependencies and package Lambda function
        working-directory: lambdas/telegram_bot
        run: |
          rm -f ../../deployment/terraform/telegram_bot.zip
          pip install -r requirements.txt -t .
          cp -r ../../shared .
          zip -r ../../deployment/terraform/telegram_bot.zip .
          sha256sum ../../deployment/terraform/telegram_bot.zip > ../../deployment/terraform/telegram_bot.zip.sha256

      # Step 4: Debug output of environment variables before applying Terraform.
      - name: Debug environment variables
        run: |
          echo "Checking secrets and environment variables:"
          echo "TELEGRAM_BOT_TOKEN: $TELEGRAM_BOT_TOKEN"
          echo "ADMIN_CHAT_ID: $ADMIN_CHAT_ID"
          echo "GOOGLE_SHEET_ID: $GOOGLE_SHEET_ID"
          echo "SERVICE_ACCOUNT_PRIVATE_KEY: [REDACTED] (Hidden for security)"
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TEST_TELEGRAM_BOT_TOKEN }}
          ADMIN_CHAT_ID: ${{ secrets.TEST_ADMIN_CHAT_ID }}
          GOOGLE_SHEET_ID: ${{ secrets.TEST_GOOGLE_SHEET_ID }}
          SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.TEST_SERVICE_ACCOUNT_PRIVATE_KEY }}

      # Step 5: Initialize and apply the Terraform configuration.
      - name: Terraform Init and Apply
        working-directory: deployment/terraform
        run: |
          terraform init \
            -backend-config="bucket=telegram-request-manager-test-terraform-state" \
            -backend-config="key=test/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_DEFAULT_REGION }}" \
            -backend-config="encrypt=true"

          # Run plan for debugging purposes
          terraform plan \
            -var="telegram_bot_token=${{ secrets.TEST_TELEGRAM_BOT_TOKEN }}" \
            -var="admin_chat_id=${{ secrets.TEST_ADMIN_CHAT_ID }}" \
            -var="google_sheet_id=${{ secrets.TEST_GOOGLE_SHEET_ID }}" \
            -var="service_account_private_key=${{ secrets.TEST_SERVICE_ACCOUNT_PRIVATE_KEY }}" \
            -var="aws_region=${{ secrets.AWS_DEFAULT_REGION }}" \
            -var-file="environments/test/terraform.tfvars"

          # Apply the changes
          terraform apply \
            -var="telegram_bot_token=${{ secrets.TEST_TELEGRAM_BOT_TOKEN }}" \
            -var="admin_chat_id=${{ secrets.TEST_ADMIN_CHAT_ID }}" \
            -var="google_sheet_id=${{ secrets.TEST_GOOGLE_SHEET_ID }}" \
            -var="service_account_private_key=${{ secrets.TEST_SERVICE_ACCOUNT_PRIVATE_KEY }}" \
            -var="aws_region=${{ secrets.AWS_DEFAULT_REGION }}" \
            -var-file="environments/test/terraform.tfvars" \
            -auto-approve

  deploy-prod:
    name: Deploy to Production Environment
    needs: deploy-test
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' # Deploy to production only through manual trigger.

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Install dependencies and package Lambda function
        working-directory: lambdas/telegram_bot
        run: |
          rm -f ../../deployment/terraform/telegram_bot.zip
          pip install -r requirements.txt -t .
          cp -r ../../shared .
          zip -r ../../deployment/terraform/telegram_bot.zip .
          sha256sum ../../deployment/terraform/telegram_bot.zip > ../../deployment/terraform/telegram_bot.zip.sha256

      - name: Terraform Init and Apply (Prod)
        working-directory: deployment/terraform
        run: |
          terraform init \
            -backend-config="bucket=telegram-request-manager-prod-terraform-state" \
            -backend-config="key=prod/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_DEFAULT_REGION }}" \
            -backend-config="encrypt=true"

          terraform apply \
            -var="telegram_bot_token=${{ secrets.PROD_TELEGRAM_BOT_TOKEN }}" \
            -var="admin_chat_id=${{ secrets.PROD_ADMIN_CHAT_ID }}" \
            -var="google_sheet_id=${{ secrets.PROD_GOOGLE_SHEET_ID }}" \
            -var="service_account_private_key=${{ secrets.PROD_SERVICE_ACCOUNT_PRIVATE_KEY }}" \
            -var="aws_region=${{ secrets.AWS_DEFAULT_REGION }}" \
            -var-file="environments/prod/terraform.tfvars" \
            -auto-approve
