name: Deploy to AWS # The name of the GitHub Actions workflow, visible in the GitHub Actions interface.

on:
  push:
    branches:
      - main # This triggers the workflow whenever code is pushed to the 'main' branch.
  workflow_dispatch: # Allows manual execution of the workflow from the GitHub Actions interface.

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # AWS Access Key, securely stored in GitHub Secrets.
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS Secret Key, securely stored in GitHub Secrets.
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }} # AWS region where the infrastructure is deployed.

jobs:
  # Deploy to Test Environment
  deploy-test:
    name: Deploy to Test Environment # Job name for deploying to the test environment.
    runs-on: ubuntu-latest # Use the latest Ubuntu virtual machine provided by GitHub Actions.

    steps:
      # Step 1: Check out the repository code into the GitHub Actions runner.
      - name: Checkout code
        uses: actions/checkout@v3 # Official GitHub Action to clone the repository into the runner.

      # Step 2: Setup Terraform for managing infrastructure.
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2 # Official Terraform GitHub Action.
        with:
          terraform_version: 1.5.0 # Specify the version of Terraform to install and use.

      # Step 3: Install dependencies and package the Lambda function for deployment.
      - name: Install dependencies and package Lambda function (Test)
        working-directory: lambdas/telegram_bot
        run: |
          rm -f ../../deployment/terraform/test_telegram_bot.zip
          pip install -r requirements.txt -t .
          cp -r ../../shared .
          zip -r ../../deployment/terraform/test_telegram_bot.zip .
          cp ../../deployment/terraform/test_telegram_bot.zip ../../deployment/terraform/telegram_bot.zip
          sha256sum ../../deployment/terraform/telegram_bot.zip > ../../deployment/terraform/telegram_bot.zip.sha256

      # Step 4: Display a partial debug of the service account private key (for verification purposes).
      - name: Debug service_account_private_key
        run: |
          echo "Service Account Private Key (first 10 chars): $(echo '${{ secrets.TEST_SERVICE_ACCOUNT_PRIVATE_KEY }}' | head -c 10) ..."

      # Step 5: Initialize and apply the Terraform configuration for the test environment.
      - name: Terraform Init and Apply (Test)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TEST_TELEGRAM_BOT_TOKEN }} # Test environment-specific token for the bot.
          ADMIN_CHAT_ID: ${{ secrets.TEST_ADMIN_CHAT_ID }} # Test admin chat ID to handle notifications.
          GOOGLE_SHEET_ID: ${{ secrets.TEST_GOOGLE_SHEET_ID }} # Test Google Sheet ID for storing responses.
          SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.TEST_SERVICE_ACCOUNT_PRIVATE_KEY }} # Test service account private key used for authentication with Google APIs.
          PRIVACY_POLICY_URL_RU: ${{ secrets.PRIVACY_POLICY_URL_RU }} # Russian version of the privacy policy URL.
          PRIVACY_POLICY_URL_EN: ${{ secrets.PRIVACY_POLICY_URL_EN }} # English version of the privacy policy URL.
          PRIVACY_POLICY_URL_KZ: ${{ secrets.PRIVACY_POLICY_URL_KZ }} # Kazakh version of the privacy policy URL.
        working-directory: deployment/terraform # Set the working directory to where Terraform files are located.
        run: |
          terraform init \
            -backend-config="bucket=telegram-request-manager-test-terraform-state" \
            -backend-config="key=test/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_DEFAULT_REGION }}" \
            -backend-config="encrypt=true"

          terraform apply \
            -var-file=environments/test/terraform.tfvars \
            -var="group_invite_link=${{ secrets.TEST_GROUP_INVITE_LINK }}" \
            -var="telegram_bot_token=${{ secrets.TEST_TELEGRAM_BOT_TOKEN }}" \
            -var="default_group_chat_id=${{ secrets.TEST_DEFAULT_GROUP_CHAT_ID }}" \
            -var="admin_chat_id=${{ secrets.TEST_ADMIN_CHAT_ID }}" \
            -var="google_sheet_id=${{ secrets.TEST_GOOGLE_SHEET_ID }}" \
            -var="service_account_type=${{ secrets.TEST_SERVICE_ACCOUNT_TYPE }}" \
            -var="service_account_project_id=${{ secrets.TEST_SERVICE_ACCOUNT_PROJECT_ID }}" \
            -var="service_account_private_key_id=${{ secrets.TEST_SERVICE_ACCOUNT_PRIVATE_KEY_ID }}" \
            -var="service_account_private_key=${{ secrets.TEST_SERVICE_ACCOUNT_PRIVATE_KEY }}" \
            -var="service_account_client_email=${{ secrets.TEST_SERVICE_ACCOUNT_CLIENT_EMAIL }}" \
            -var="service_account_client_id=${{ secrets.TEST_SERVICE_ACCOUNT_CLIENT_ID }}" \
            -var="service_account_auth_uri=${{ secrets.TEST_SERVICE_ACCOUNT_AUTH_URI }}" \
            -var="service_account_token_uri=${{ secrets.TEST_SERVICE_ACCOUNT_TOKEN_URI }}" \
            -var="service_account_auth_provider_cert_url=${{ secrets.TEST_SERVICE_ACCOUNT_AUTH_PROVIDER_CERT_URL }}" \
            -var="service_account_client_cert_url=${{ secrets.TEST_SERVICE_ACCOUNT_CLIENT_CERT_URL }}" \
            -var="aws_region=${{ secrets.AWS_DEFAULT_REGION }}" \
            -var="privacy_policy_url_ru=${{ secrets.PRIVACY_POLICY_URL_RU }}" \
            -var="privacy_policy_url_en=${{ secrets.PRIVACY_POLICY_URL_EN }}" \
            -var="privacy_policy_url_kz=${{ secrets.PRIVACY_POLICY_URL_KZ }}" \
            -auto-approve

  # Deploy to Production Environment (disabled by default for manual activation).
  deploy-prod:
    name: Deploy to Production Environment # Job name for deploying to the production environment.
    needs: deploy-test # Ensure this job runs only after the test deployment succeeds.
    runs-on: ubuntu-latest # Use the latest Ubuntu virtual machine provided by GitHub Actions.
    if: false # Temporarily disable the production deployment.

    steps:
      # Step 1: Check out the repository code into the GitHub Actions runner.
      - name: Checkout code
        uses: actions/checkout@v3 # Official GitHub Action to clone the repository into the runner.

      # Step 2: Setup Terraform for managing infrastructure.
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2 # Official Terraform GitHub Action.
        with:
          terraform_version: 1.5.0 # Specify the version of Terraform to install and use.

      # Step 3: Install dependencies and package the Lambda function for deployment.
      - name: Install dependencies and package Lambda function (Prod)
        working-directory: lambdas/telegram_bot
        run: |
          rm -f ../../deployment/terraform/prod_telegram_bot.zip
          pip install -r requirements.txt -t .
          cp -r ../../shared .
          zip -r ../../deployment/terraform/prod_telegram_bot.zip .
          cp ../../deployment/terraform/prod_telegram_bot.zip ../../deployment/terraform/telegram_bot.zip
          sha256sum ../../deployment/terraform/telegram_bot.zip > ../../deployment/terraform/telegram_bot.zip.sha256

      # Step 4: Display a partial debug of the service account private key (for verification purposes).
      - name: Debug service_account_private_key
        run: |
          echo "Service Account Private Key (first 10 chars): $(echo '${{ secrets.PROD_SERVICE_ACCOUNT_PRIVATE_KEY }}' | head -c 10) ..."

      # Step 5: Initialize and apply the Terraform configuration for the production environment.
      - name: Terraform Init and Apply (Prod)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.PROD_TELEGRAM_BOT_TOKEN }} # Production environment-specific token for the bot.
          ADMIN_CHAT_ID: ${{ secrets.PROD_ADMIN_CHAT_ID }} # Production admin chat ID to handle notifications.
          GOOGLE_SHEET_ID: ${{ secrets.PROD_GOOGLE_SHEET_ID }} # Production Google Sheet ID for storing responses.
          SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.PROD_SERVICE_ACCOUNT_PRIVATE_KEY }} # Production service account private key used for authentication with Google APIs.
          PRIVACY_POLICY_URL_RU: ${{ secrets.PRIVACY_POLICY_URL_RU }} # Russian version of the privacy policy URL.
          PRIVACY_POLICY_URL_EN: ${{ secrets.PRIVACY_POLICY_URL_EN }} # English version of the privacy policy URL.
          PRIVACY_POLICY_URL_KZ: ${{ secrets.PRIVACY_POLICY_URL_KZ }} # Kazakh version of the privacy policy URL.
        working-directory: deployment/terraform # Set the working directory to where Terraform files are located.
        run: |
          terraform init \
            -backend-config="bucket=telegram-request-manager-prod-terraform-state" \
            -backend-config="key=prod/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_DEFAULT_REGION }}" \
            -backend-config="encrypt=true"

          terraform apply \
            -var-file=environments/prod/terraform.tfvars \
            -var="group_invite_link=${{ secrets.PROD_GROUP_INVITE_LINK }}" \
            -var="telegram_bot_token=${{ secrets.PROD_TELEGRAM_BOT_TOKEN }}" \
            -var="default_group_chat_id=${{ secrets.PROD_DEFAULT_GROUP_CHAT_ID }}" \
            -var="admin_chat_id=${{ secrets.PROD_ADMIN_CHAT_ID }}" \
            -var="google_sheet_id=${{ secrets.PROD_GOOGLE_SHEET_ID }}" \
            -var="service_account_type=${{ secrets.PROD_SERVICE_ACCOUNT_TYPE }}" \
            -var="service_account_project_id=${{ secrets.PROD_SERVICE_ACCOUNT_PROJECT_ID }}" \
            -var="service_account_private_key_id=${{ secrets.PROD_SERVICE_ACCOUNT_PRIVATE_KEY_ID }}" \
            -var="service_account_private_key=${{ secrets.PROD_SERVICE_ACCOUNT_PRIVATE_KEY }}" \
            -var="service_account_client_email=${{ secrets.PROD_SERVICE_ACCOUNT_CLIENT_EMAIL }}" \
            -var="service_account_client_id=${{ secrets.PROD_SERVICE_ACCOUNT_CLIENT_ID }}" \
            -var="service_account_auth_uri=${{ secrets.PROD_SERVICE_ACCOUNT_AUTH_URI }}" \
            -var="service_account_token_uri=${{ secrets.PROD_SERVICE_ACCOUNT_TOKEN_URI }}" \
            -var="service_account_auth_provider_cert_url=${{ secrets.PROD_SERVICE_ACCOUNT_AUTH_PROVIDER_CERT_URL }}" \
            -var="service_account_client_cert_url=${{ secrets.PROD_SERVICE_ACCOUNT_CLIENT_CERT_URL }}" \
            -var="aws_region=${{ secrets.AWS_DEFAULT_REGION }}" \
            -var="privacy_policy_url_ru=${{ secrets.PRIVACY_POLICY_URL_RU }}" \
            -var="privacy_policy_url_en=${{ secrets.PRIVACY_POLICY_URL_EN }}" \
            -var="privacy_policy_url_kz=${{ secrets.PRIVACY_POLICY_URL_KZ }}" \
            -auto-approve
